//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHI_TIET_HD = new HashSet<CHI_TIET_HD>();
        }
    
        public int ID { get; set; }
        public string TEN_SACH { get; set; }
        public string TAC_GIA { get; set; }
        public string NHA_XB { get; set; }
        public double GIA_TIEN { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<int> ID_THE_LOAI { get; set; }
        public string HINH_ANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HD> CHI_TIET_HD { get; set; }
        public virtual THE_LOAI_SACH THE_LOAI_SACH { get; set; }
    }
}
